language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_scaffold.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "OENtQByqdkkzHZJM36BQfuiD21A/SSjegwucanees63pwWyLOEe+arWGmfhUCU98zvVcH4e2Vealex9FJgbAjPm/4lXC4gHyQPgqe0+a9vQDDdb6UiumAdsaWqkZoH0z5yJ8dyB4h+kIl02giiM6N0o3FBAmL0DI+RMnudwFbmFQDFF1FXxbnIe1Bwa0b/aGiMv/1zgydbFYRFv1I75ZQXg+MQ2svPL9lmWmeBlM/+hN4qb4Wjn4LZ2GVbfIz7c0yPqPKv8Bg0xPjad/IVhkceKrd9qO8lC8Tyesd7JATBluLiXAATZZlaYJA1exib5pWtn7XUnm8GUIVS9rodSrMKfpFpAGU5ZBzQl+VC9e4PoSowNPrE7oH849mTussTHqPgjIj0raeu0HamjtJVJ7PXnOnqsdNWJzwnJxQE48p5TCaMCbjGFmYZOWfPoBkNsyLL8zvb5+cYwRRoDnNgZdPvon/WeBnyNzNcb63pt8I25v35qhSwXaOZIEN2GUKPO1ogRlaDOj6QTfcpjnyVUbQyRC+0GdoJveFHdFakSUnwn2oXryj2FhZQ73sGvvdIf+3e6seV6ONw3JqoRXMvew5La2TNQVsmSftBjAovW02CIRHYnESN5XEPSNDALJ/qerIbJnM73g84KxkgeV7OQtrcPt+UvamdRhxfa0rIGj12A="
