language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_scaffold.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "gJhARkoj6Im0/Q1Eo4xmvqL0cPyd9U5woPGvsJfBGdjDx++8ZhJeTziQB7jFkrbWCErjy/XQvruNSQG186DzDxdblIq3xTLNdH0ub//UM5ags8/esyyGVtQ7exZhyYInMHg3tpFQbr5aVx779E/5ginseDMiPMhFRCaiLcX3Ktq200FCX0zvIdLVoethEvLrrKtN9vYIw94fLPooyJqUIhMruoJzTk2EDeEoUSzqr2j7/Gr1U2oRKjygdTAJvXvRfX2EdgPw8WFnwSH8gVI+L+aa7PKVIn2PJhL0Tjcu52jYQahPKU+G902oa1Ut6O5Ob2nzuyy6/28aRHyXS1BeYkgteqKfGoAMRVVgE0SBb4P3X9sWcTM/LweACMyfVwHCJYlY1x+ieRloogSV8ES9U7t7fdRjPzQ061Z+QZjXqxbgN/bM95QkWQVSLJScuRP47XBYQ3NMHH30287ihkx1cL8CmtuhpevjfWPu/n8v69cgNOO7au9oBf49xxHnXJCGGc7iw3NQfVN0jUDX2NiEukHjjb90D3yd8JYt5oJDkJp/Bn5l4g8Go23yR8+2VDRqtpacWictrL6Yrmz41mAsNVolAI1tdM+pKsbTiZ454K12usOAMtuWvbRpDaLyhMQJnwFDrgMo4VsAOhah5CS522bzoX26mRdQIeLRjvZOf7k="
